version: '3.4'

services:
  totoropara:
    image: ghcr.io/lixiang810/totoro-paradise:latest
    container_name: totoro-paradise
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
